<?php

namespace Dev\App\Wetzikon\Com\Form;

use Dev\App\Wetzikon\Data\Poi\Poi;
use Dev\App\Wetzikon\Data\Poi\PoiReader;
use Dev\App\Wetzikon\Data\Poi\PoiUpdate;
use Nemundo\Admin\Com\Form\AbstractAdminEditForm;
use Nemundo\Admin\Com\Form\AbstractAdminForm;
use Nemundo\Admin\Com\ListBox\AdminLargeTextBox;
use Nemundo\Admin\Com\ListBox\AdminTextBox;
use Nemundo\Core\Type\Geo\GeoCoordinate;

class PoiForm extends AbstractAdminEditForm
{

    /**
     * @var AdminTextBox
     */
    private $titel;

    /**
     * @var AdminLargeTextBox
     */
    private $text;


    /**
     * @var AdminTextBox
     */
    private $coordinate;

    public function getContent()
    {

        $this->titel=new AdminTextBox($this);
        $this->titel->label='Titel';
        $this->titel->validation=true;

        $this->text=new AdminLargeTextBox($this);
        $this->text->label='Text';

        $this->coordinate=new AdminTextBox($this);
        $this->coordinate->label='Coordinate';
        $this->coordinate->validation=true;




        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function loadUpdateForm()
    {

        $poiRow=(new PoiReader())->getRowById($this->dataId);

        $this->titel->value=$poiRow->titel;
        $this->text->value= $poiRow->text;
        $this->coordinate->value=$poiRow->coordinateText;

        /*$this->coordinate->validation=false;
        $this->coordinate->visible=false;*/


        // TODO: Implement loadUpdateForm() method.
    }


    protected function onSave()
    {

        $data=new Poi();
        $data->titel=$this->titel->getValue();
        $data->text=$this->text->getValue();
        $data->coordinateText= $this->coordinate->getValue();
        $data->coordinate->fromText($this->coordinate->getValue());
        $data->save();


        // TODO: Implement onSubmit() method.
    }



    protected function onUpdate()
    {

        $data=new PoiUpdate();
        $data->titel=$this->titel->getValue();
        $data->text=$this->text->getValue();
        $data->coordinateText= $this->coordinate->getValue();
        $data->coordinate->fromText($this->coordinate->getValue());
        $data->updateById($this->dataId);

        // TODO: Implement onUpdate() method.
    }


}