<?php

namespace Dev\App\Wetzikon\Com\Form;

use Dev\App\Wetzikon\Data\Poi\Poi;
use Nemundo\Admin\Com\Form\AbstractAdminForm;
use Nemundo\Admin\Com\ListBox\AdminLargeTextBox;
use Nemundo\Admin\Com\ListBox\AdminTextBox;
use Nemundo\Core\Type\Geo\GeoCoordinate;

class PoiForm extends AbstractAdminForm
{

    /**
     * @var AdminTextBox
     */
    private $titel;

    /**
     * @var AdminLargeTextBox
     */
    private $text;


    /**
     * @var AdminTextBox
     */
    private $coordinate;

    public function getContent()
    {

        $this->titel=new AdminTextBox($this);
        $this->titel->label='Titel';
        $this->titel->validation=true;

        $this->text=new AdminLargeTextBox($this);
        $this->text->label='Text';

        $this->coordinate=new AdminTextBox($this);
        $this->coordinate->label='Coordinate';
        $this->coordinate->validation=true;


        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {



        $data=new Poi();
        $data->titel=$this->titel->getValue();
        $data->text=$this->text->getValue();

        $data->coordinate->fromText($this->coordinate->getValue());
        $data->save();


        // TODO: Implement onSubmit() method.
    }


}