<?php

namespace Dev\App\Wetzikon\Com\Form;

use Dev\App\Wetzikon\Data\PoiBild\PoiBild;
use Nemundo\Admin\Com\Form\AbstractAdminForm;
use Nemundo\Admin\Com\ListBox\AdminFileUpload;
use Nemundo\Html\Form\Input\AcceptFileType;

class PoiImageForm extends AbstractAdminForm
{

    public $poiId;

    /**
     * @var AdminFileUpload
     */
    private $image;

    public function getContent()
    {

        $this->image=new AdminFileUpload($this);
        $this->image->multiUpload=true;
        $this->image->acceptFileType=AcceptFileType::IMAGE;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {

        foreach ($this->image->getMultiFileRequest() as $fileRequest) {

            $data=new PoiBild();
            $data->poiId=$this->poiId;
            $data->bild->fromFileRequest($fileRequest);
            $data->save();


        }

        // TODO: Implement onSubmit() method.
    }



}