<?php

namespace Nemundo\Content\Index\Geo\Action;

use Nemundo\Content\Action\AbstractActionForm;
use Nemundo\Package\Bootstrap\FormElement\BootstrapGeoCoordinate;

class GeoIndexForm extends AbstractActionForm
{

    /**
     * @var BootstrapGeoCoordinate
     */
    private $coordinate;

    public function getContent()
    {
        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {
        // TODO: Implement onSubmit() method.
    }


}