<?php

namespace Nemundo\Content\Com\Card;

use Nemundo\Admin\Com\Card\AdminCard;
use Nemundo\Content\Builder\ContentBuilder;

class ContentCard extends AdminCard
{

    public $contentId;

    public $content;

    public function getContent()
    {

        $content= (new ContentBuilder())->getContent($this->contentId);

        $this->cardTitle=$content->getSubject();
        $content->getDefaultView($this);


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}