<?php

namespace Nemundo\Admin\Com\Navbar;

use Nemundo\Com\Utility\UniqueComName;
use Nemundo\Html\Block\Div;
use Nemundo\Web\Site\AbstractSite;

class AdminNavbarDropdown extends Div
{


    public $dropdownLabel;


    private $dropdown;


    private $submenuContent;



    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub


        $this->dropdown = new AdminNavbarSubmenuDropdownHyperlink($this);
        $this->dropdown->addCssClass('admin-navbar-dropdown-link');
        $this->submenuContent = new Div($this);

    }


    public function getContent()
    {

        //$submenu =new Div($menu);



       // new Hyperlink($submenu);  // SiteHyperlink($menu);
        $this->dropdown->content=$this->dropdownLabel;  // site->title;


        $dropdownId = 'dropone-' . (new UniqueComName())->getUniqueName();

        $this->dropdown->addAttribute('onclick', 'hideNavbarDropdownMenu(); document.getElementById(\'' . $dropdownId . '\').classList.toggle(\'admin-dropdown-show\');');
        //$this->dropdown->addAttribute('onclick', 'checkDropdownClick(); document.getElementById(\'' . $dropdownId . '\').classList.toggle(\'admin-dropdown-show\');');


        $this->submenuContent->id = $dropdownId;
        //$this->submenuContent->addCssClass('admin-dropdown-content');
        $this->submenuContent->addCssClass('admin-navbar-submenu-content');
        //parent::addContainer($this->content);

        //$submenu = new Div($menu);
        //$submenu->addCssClass('admin-navbar-submenu');

        /*$p=new Paragraph($submenu);
        $p->content= 'Submenu: '.$site->title;*/


        //$menuActive = false;
        //foreach ($site->getMenuActiveSite() as $subSite) {
          //  if ($subSite->menuActive) {
                //$menuActive = true;

               // $hyperlink = new AdminSubmenuSiteHyperlink($submenuContent);  // new SiteHyperlink($submenuContent);
                /*$hyperlink->addCssClass('admin-navbar-link');
                $hyperlink->addCssClass('admin-navbar-submenu-link');*/
                //$hyperlink->site = $subSite;

            //}
        //}


        return parent::getContent(); // TODO: Change the autogenerated stub

    }


    public function addSubsite(AbstractSite $site) {


        $hyperlink = new AdminSubmenuSiteHyperlink($this->submenuContent);  // new SiteHyperlink($submenuContent);
        /*$hyperlink->addCssClass('admin-navbar-link');
        $hyperlink->addCssClass('admin-navbar-submenu-link');*/
        $hyperlink->site = $site;


    }


}