<?php

namespace Nemundo\Admin\Com\Form\Geo;

use Nemundo\Admin\Com\ListBox\AdminTextBox;
use Nemundo\Html\Block\Div;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;

class AdminGeoCoordinateTextBox extends Div
{

    /**
     * @var BootstrapTextBox
     */
    private $lat;

    /**
     * @var BootstrapTextBox
     */
    private $lon;


    public function getContent()
    {

        $this->lat=new AdminTextBox($this);
        //$this->la

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

    public function getGeoCoordinate() {



    }

}