<?php

namespace Nemundo\Admin\Com\ListGroup;

use Nemundo\Html\Block\Div;

class AdminListGroup extends Div
{

    public function getContent()
    {

        $this->addCssClass('admin-list-group');

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}