<?php

namespace Parlament\Com\Container;

use Nemundo\Com\Html\Listing\UnorderedList;
use Nemundo\Html\Block\Div;
use Nemundo\Html\Heading\H1;
use Parlament\Data\Kommission\KommissionReader;
use Parlament\Data\KommissionRatsmitglied\KommissionRatsmitgliedReader;

class KommissionListContainer extends Div
{

    public function getContent()
    {


        $kommissionReader=new KommissionReader();
        $kommissionReader->filter->andEqual($kommissionReader->model->aktiv,true);
        foreach ($kommissionReader->getData() as $kommissionRow) {

            $h1=new H1($this);
            $h1->content=$kommissionRow->kommission;

            $ul=new UnorderedList($this);

            $kommissionReader=new KommissionRatsmitgliedReader();
            $kommissionReader->model->loadRatsmitglied();
            $kommissionReader->filter->andEqual($kommissionReader->model->kommissionId, $kommissionRow->id);
            //$kommissionReader->filter->andEqual($kommissionReader->model->aktiv,true);
            //$kommissionReader->filter->andEqual($kommissionReader->model->kommission->aktiv,false);
            foreach ($kommissionReader->getData() as $kommissionRatsmitgliedRow) {
                $ul->addText($kommissionRatsmitgliedRow->ratsmitglied->getVornameName());
            }




        }





        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}