<?php

namespace Nemundo\Admin\Com\ListBox;

use Nemundo\Core\Language\LanguageCode;

class AdminSearchTextBox extends AdminTextBox
{

    public function getContent()
    {

        //$this->textInput->placeholder=[];
        $this->placeholder[LanguageCode::EN] = 'Search';
        $this->placeholder[LanguageCode::DE] = 'Suchen';

        //$this->placeholder = 'Search';


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}