<?php

namespace Parlament\Com\Card;

use Nemundo\Admin\Com\Card\AdminCard;
use Nemundo\Admin\Com\Image\AdminImage;
use Nemundo\Bfs\Gemeinde\Parameter\RatsmitgliedParameter;
use Nemundo\Com\Html\Hyperlink\SiteHyperlink;
use Nemundo\Html\Block\ContentDiv;
use Parlament\Data\Ratsmitglied\RatsmitgliedRow;
use Parlament\Site\Ratsmitglied\RatsmitgliedItemSite;

class RatsmitgliedItemCard extends AdminCard
{

    /**
     * @var RatsmitgliedRow
     */
    public $ratsmitgliedRow;

    public function getContent()
    {


        $this->cardTitle=$this->ratsmitgliedRow->getVornameName();
        //$item->addCssClass('ratsmitglied-item');

        //$item->addAttribute('draggable','true');

        /*
                    $title=new ContentDiv($item);
                    $title->addCssClass('ratsmitglied-item-title');
                    $title->content=$ratsmitgliedRow->getVornameName();*/


        $hyperlink = new SiteHyperlink($this);
        $hyperlink->site=clone(RatsmitgliedItemSite::$site);
        $hyperlink->site->addParameter(new RatsmitgliedParameter($this->ratsmitgliedRow->id));
        $hyperlink->showSiteTitle=false;


        $img= new AdminImage($hyperlink);  // new Img($item);
        //$img->addCssClass('ratsmitglied-item-image');
        $img->src=$this->ratsmitgliedRow->bild->getUrl();

        $item=new ContentDiv($this);
        //$item->addCssClass('ratsmitglied-item-text');
        $item->content = $this->ratsmitgliedRow->kanton->kanton;

        $item=new ContentDiv($item);
        $item->content = $this->ratsmitgliedRow->fraktion->fraktion;





        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}