<?php

namespace Parlament\Com\Small;

use Nemundo\Html\Formatting\Small;

class SourceSmall extends Small
{

    public function getContent()
    {

        $this->content='Quelle: Parlamentsdienste der Bundesversammlung, Bern / 20.05.2022';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}